version: '3.4'

services:
  tfheppy:
    image: tfheppy
    build:
      context: .
      dockerfile: ./docker/Dockerfile.tutrial
    volumes:
      - ./:/app/
    working_dir: /app/tutorial
    command: python3 test.py
    tty: true
